// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx373r_Cqc5gHZNpPH23fUvSTFq7M9mpg',
    appId: '1:557296019628:android:d216c25380eb2d8a609709',
    messagingSenderId: '557296019628',
    projectId: 'emerapp-59c53',
    storageBucket: 'emerapp-59c53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHfa_cZOaN96b15Lf2YGGfor-LmzVMQoY',
    appId: '1:557296019628:ios:d2a99e5269937b6e609709',
    messagingSenderId: '557296019628',
    projectId: 'emerapp-59c53',
    storageBucket: 'emerapp-59c53.appspot.com',
    androidClientId: '557296019628-mn0tgk92v0plq5b0l0ctrqebsf48q4qo.apps.googleusercontent.com',
    iosClientId: '557296019628-1hr9hc4dss6pg89hqehs3f618knqulaf.apps.googleusercontent.com',
    iosBundleId: 'com.emerapp.app',
  );
}
